import React, { useState } from 'react';
import { X, Copy, Check, Download, Share2 } from 'lucide-react';
import { Language, GapAnalysis } from '../types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: GapAnalysis;
  lang: Language;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  analysis,
  lang,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = () => {
    return `# Õpilausuja — Learning & Career Path: ${analysis.goalTitle}

**Readiness / Sobivus:** ${analysis.readinessScore}%
**Created:** ${new Date(analysis.createdAt).toLocaleDateString()}

## Current Skills / Mida juba oskad:
${analysis.alreadyHave.map(s => `- [x] ${s.name}`).join('\n')}

## Target Gaps / Mida veel vajad:
${analysis.stillNeed.map(s => `- [ ] ${s.name}`).join('\n')}

## Sequenced Learning Path / Õpimisteekond:
${analysis.path.map(p => `### Step ${p.order}: ${p.title} ${p.completed ? '✅ (Completed)' : '⏳'}
- **Why this matters:** ${p.why}
- **Estimated Effort:** ${p.estimatedEffort}
- **Suggested Resource:** ${p.suggestedResource}
- **Related Competency:** ${p.relatedSkill}
`).join('\n')}

---
*Generated by Õpilausuja — See what you already know. Discover what comes next.*
`;
  };

  const markdownText = generateMarkdown();

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdownText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback
    }
  };

  const handleDownload = () => {
    const blob = new Blob([markdownText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `opilausuja-path-${analysis.goalTitle.toLowerCase().replace(/\s+/g, '-')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div 
        className="bg-white rounded-3xl max-w-lg w-full max-h-[85vh] flex flex-col shadow-2xl border border-slate-200 p-5 sm:p-6 animate-in zoom-in-95 duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between pb-3 border-b border-slate-100">
          <div className="flex items-center gap-2">
            <Share2 className="w-5 h-5 text-teal-600" />
            <h3 className="font-bold text-slate-900 text-base">
              {lang === 'et' ? 'Ekspordi või jaga teekonda' : 'Export & Share Roadmap'}
            </h3>
          </div>
          <button onClick={onClose} className="p-1 rounded-full text-slate-400 hover:text-slate-700 cursor-pointer">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="py-3 flex-1 overflow-y-auto font-mono text-xs text-slate-700 bg-slate-50 p-3 rounded-xl border border-slate-200 my-2 whitespace-pre-wrap">
          {markdownText}
        </div>

        <div className="pt-3 flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex-1 py-2.5 bg-teal-600 hover:bg-teal-700 text-white font-bold text-xs rounded-xl flex items-center justify-center gap-1.5 cursor-pointer shadow-xs transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? (lang === 'et' ? 'Kopeeritud!' : 'Copied!') : (lang === 'et' ? 'Kopeeri Markdown' : 'Copy Markdown')}</span>
          </button>

          <button
            onClick={handleDownload}
            className="px-4 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs rounded-xl flex items-center gap-1.5 cursor-pointer transition-colors"
          >
            <Download className="w-4 h-4" />
            <span>{lang === 'et' ? 'Laadi alla (.md)' : 'Download .md'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
